dist: bionic
language: python
python:
  - '3.6'
  - '3.7'
services:
  - redis-server
matrix:
  - fast_finish: true
install:
  - pip install -r requirements.txt
script:
  - pytest

deploy:
  - provider: releases
    api_key:
      secure: "LNiNRyMec/Yb8a3L0CUlecQ2KT9EVrsaVj+xyYGffKc4RERKuFVZwGG+/hc87MyObKFBKhfijtl1qa62b08cNya81MUVv4cZloVSYrjg9xo7uaQXGfDTfCOyhWATPtuMqLZJyDHg1lyMpLiVBCaBSho6nuPD8UC/1NhuRtKTClen6BgQI1Sq41c1Cev2kNvDHppeGvh6+i0kpA+4EkHw0In50TBuZEt/S934q+OPeopdWK72p9CF2h7F8ZJAkw2lAWGYjaqEYhUzpeuGij/NFseXcy4S2vAbI+2tar/Xyp+xDrZo4AqnmNqeyapKhLAWiKZzk0bTominJHzwzYivqJogw91pcosjixR2G4Z5JFiddOSUriDTZKLNX1eq+1HGR+qpY/3u5JGQ3+GNkRlfja8VA4WbRZsjcvhcfXFdGh2hd/pa6nDl6pZ2M8oVfCYBzXGCMvOhiULKjMzzfdQXX+520ELZ75rkOLWasSt9rwFcCDnf5Rm6R4pT6AqjEc1m5yiQBNcB9d7lakOMjqu6/1gbOa1QVZPaS9ct1XHq7yizS66+4NEvEKgyPuLSjdN6PFjwobOwKf3cek805srgrwE3B4zM/PKgEidAQe8KQclAPjUJQsJW9QaCe6HVfGpNZeKYxBxek8Tu3OtaWbNWkYrkbZR/ZrSDGaKIqJaJcBg="
    file_glob: true
    file: dist/python-squash-*.tar.gz
    on:
      repo: eoranged/squash
      tags: true
  - provider: pypi
    user: eoranged
    password:
      secure: "KOJHjUnvZDM5kyi932+6GzSUYBJkcTw5ekI4zLbsug86Nowc5VA6s2egBr2BzR3b9DuGIdl/R3dP/lCpEhZxdcbXph2WDGDHh2gYiQiteDeX0sxJV3/QeNZvgpv9sp9RCJ4Yb2L0CBHpqM/B5HyRbcbjorcGQTjbH3nEuINOhMNzU/Nyf+2nu+D5bEgEsxDbr9AaSCcm5fykMQTgzkj6I4SaDPQpYrzEeObLgZUgOih7OuPmm8HD2aVhzJenayzm0xF8pb6Kxgs5zXkAV+ykPUVcbc3sU+AjSs4HNaxltAP+hNddfBKSGN0vpLoGuVSqok2PyI+uDuCE6Rjh2c8LRKdINeenRUALNPvDjtiXAMQeIAAMlAu2dz4FLHu3SgkLsenXAbRTMgHX5rNIP+cIjbWHb2g9mPXZa2wgN3ALs9HVyOHMQ6C5LbR++im4vCqZP50fnRLApKfUgWluMvEzrgnLFofQ8ZcOkMJI/++W32EJtshh6xEnRiiyJbn9ZU031LXpgAWK+Gb8pY5wyRIRH5bK33+AD3M2iuj4yXhziDzy8K19wQvgMWancIB4IREHZXnR9Pqjnn5al77UoR59WmIAR1QFPvdoqBqSrQMSP19+VyxMN1n2EEElidKIRhdiT2p3poevKvxE+58ZszhSeNeYQqeYFBzQz0T++2/3p/Q="
    skip_existing: true
    skip_cleanup: true
    on:
      repo: eoranged/squash
      tags: true
