dist: bionic
language: python
python:
  - '3.6'
  - '3.7'
services:
  - redis-server
matrix:
  - fast_finish: true
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest

before_deploy:
  - python setup.py sdist

deploy:
  - provider: releases
    api_key:
      secure: "LNiNRyMec/Yb8a3L0CUlecQ2KT9EVrsaVj+xyYGffKc4RERKuFVZwGG+/hc87MyObKFBKhfijtl1qa62b08cNya81MUVv4cZloVSYrjg9xo7uaQXGfDTfCOyhWATPtuMqLZJyDHg1lyMpLiVBCaBSho6nuPD8UC/1NhuRtKTClen6BgQI1Sq41c1Cev2kNvDHppeGvh6+i0kpA+4EkHw0In50TBuZEt/S934q+OPeopdWK72p9CF2h7F8ZJAkw2lAWGYjaqEYhUzpeuGij/NFseXcy4S2vAbI+2tar/Xyp+xDrZo4AqnmNqeyapKhLAWiKZzk0bTominJHzwzYivqJogw91pcosjixR2G4Z5JFiddOSUriDTZKLNX1eq+1HGR+qpY/3u5JGQ3+GNkRlfja8VA4WbRZsjcvhcfXFdGh2hd/pa6nDl6pZ2M8oVfCYBzXGCMvOhiULKjMzzfdQXX+520ELZ75rkOLWasSt9rwFcCDnf5Rm6R4pT6AqjEc1m5yiQBNcB9d7lakOMjqu6/1gbOa1QVZPaS9ct1XHq7yizS66+4NEvEKgyPuLSjdN6PFjwobOwKf3cek805srgrwE3B4zM/PKgEidAQe8KQclAPjUJQsJW9QaCe6HVfGpNZeKYxBxek8Tu3OtaWbNWkYrkbZR/ZrSDGaKIqJaJcBg="
    file_glob: true
    file: dist/python-squash-*.tar.gz
    skip_existing: true
    skip_cleanup: true
    on:
      repo: eoranged/squash
      tags: true
  - provider: pypi
    twine_version: 1.13.0
    user: squash-deployer
    password:
      secure: "hxyg51/GNjRpbeH8kfKheLk4YQGo6XcGY3LaafhmQWO4C39UlhSOjYf3C45gcBxke8XuQcGNuLjPSQ4j/o6SkJP8NK/3bDS31oeQtf4KgOh/hmK630/ZYT5pgdTBKvR9+V0tP42VHpLdlTr4lqAKIj4LxdI5mT7FlBQtwPvy6a23RWG7YfOr9YrT8+S8ZNniWALKSB7MeAufaNxBpXs1C9eMxZSWh0vcALDNzZLAMBeNxHTd8PDSjEhsOcECNkYNQ7VKeLoPyRX/mdWOjrkS5bhxhww+XF+b7h6D/rFThfv2O/BZiLyBT+XgKYOzlopC5FuU3Sv2fD7KZcYf/bjvgkRxodiwDPwU8ilqQeI5EDqivNvxCNVchzI0tv+PBSrsN8zP5IpSahC3wZC2ummTLUA5CXMTCy7SrX5k7VRKcZX6ZcJyVxQdI0WrWUzMj8TYCAqCRsofJRDC5G5IC/So69K8+YsvOC1bWc2VHDkO+zh02QsMUKCp50cZXNhxE3wGyoas1o+/BtzbYqW8r2NFNfWzMJARXFegNmMLdTgFod/d13t4/LJo0dfo1P9OBiY5PPZjFMp3XZ/au2ODkXZ8lPtqgwfDKY1yRjh2YQ9+TCZ2efoGO/2vckg3FTSb7ZTS3poOpJQnAuQ2ZRvg7qWRFr+72eu5zXzyG7N5FvzTtho="
    skip_existing: true
    skip_cleanup: true
    on:
      repo: eoranged/squash
      tags: true
