dist: bionic
language: python
python:
  - '3.6'
  - '3.7'
services:
  - redis-server
matrix:
  - fast_finish: true
install:
  - pip install -r requirements.txt
script:
  - pytest

before_deploy:
  - python setup.py sdist

deploy:
  - provider: releases
    api_key:
      secure: "LNiNRyMec/Yb8a3L0CUlecQ2KT9EVrsaVj+xyYGffKc4RERKuFVZwGG+/hc87MyObKFBKhfijtl1qa62b08cNya81MUVv4cZloVSYrjg9xo7uaQXGfDTfCOyhWATPtuMqLZJyDHg1lyMpLiVBCaBSho6nuPD8UC/1NhuRtKTClen6BgQI1Sq41c1Cev2kNvDHppeGvh6+i0kpA+4EkHw0In50TBuZEt/S934q+OPeopdWK72p9CF2h7F8ZJAkw2lAWGYjaqEYhUzpeuGij/NFseXcy4S2vAbI+2tar/Xyp+xDrZo4AqnmNqeyapKhLAWiKZzk0bTominJHzwzYivqJogw91pcosjixR2G4Z5JFiddOSUriDTZKLNX1eq+1HGR+qpY/3u5JGQ3+GNkRlfja8VA4WbRZsjcvhcfXFdGh2hd/pa6nDl6pZ2M8oVfCYBzXGCMvOhiULKjMzzfdQXX+520ELZ75rkOLWasSt9rwFcCDnf5Rm6R4pT6AqjEc1m5yiQBNcB9d7lakOMjqu6/1gbOa1QVZPaS9ct1XHq7yizS66+4NEvEKgyPuLSjdN6PFjwobOwKf3cek805srgrwE3B4zM/PKgEidAQe8KQclAPjUJQsJW9QaCe6HVfGpNZeKYxBxek8Tu3OtaWbNWkYrkbZR/ZrSDGaKIqJaJcBg="
    file_glob: true
    file: dist/python-squash-*.tar.gz
    skip_existing: true
    skip_cleanup: true
    on:
      repo: eoranged/squash
      tags: true
  - provider: pypi
    twine_version: 1.13.0
    user: eoranged
    password:
      secure: "OeWxsQoOcuG57izZrixItksgFE00LuFcaETHTDPH4e6AwsPBprJDvIutu32eK8d0rQDYMmnQelnJa4+JqikZO51bczBnc+TbQHCnJcA/htTL9bdlDtVGHXSigye1JkSmVymgiFTbdBJak+l2fu5VLqKw8I5fla8yxOAjvB2V4TTdoi8p9plzUgMeySX2L+ZAHQ4Rnzj39JLNbHS9hlt1HqwB9nsBrnnNp71aJYSu/jOWVG7YQyReDpJ7OfXFpc4ULyD3OlSfIxIkB1JiL4kjN3Ofx4/o+PBlX8Dwp6h1xExbgSfsYliApUjGQrBIwzuOWzRiDBLPgF4Sh/aiREVzksOJNdn77/4X+XuXFwTOEG57Eaeaax8PU4786gppr1wlQK34UjDq4/RsbdCE0ubVATRt781WhPpZWA+vqBE3DbDaftWRZ995ip53WpD4IXYpEOvFP7e/QjxGMf0PVbVIr39fec9tYMGvpcnhw5drFFFIzISWzfedv6k1UYYr4uV5I5KCNtS+XVGIh5ou2b6RC4jKl87NZlqElerQeZEEF64Ur7J28EdW2x7FD4s4k/UB36P0GiK049xWWK58CN1oR3e9h1C+LlxJuOk4OXSq2jTHKNxClZ+SMjzxbqpMoUhQTMX2keyKb1jCIJR3xui62jsLJ/b/uiZ4mnJw0WD3bFs="
    skip_existing: true
    skip_cleanup: true
    on:
      repo: eoranged/squash
      tags: true
