dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
services:
  - redis-server
matrix:
  - fast_finish: true
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
- pytest
